import { DatabaseOption, User } from "@types";

// userid will actually be generated automatically by postgres
const sampleUsers = [
  {
    username: "user1_za",
    fullname: "John Smith",
    email: "john.smith@email.com",
    passwordhash: "hash1",
    creationdate: null,
    database: "za" as DatabaseOption,
  },
  {
    username: "user2_br",
    fullname: "Maria Silva",
    email: "maria.silva@email.com",
    passwordhash: "hash2",
    creationdate: null,
    database: "br" as DatabaseOption,
  },
  {
    username: "user3_us",
    fullname: "Mike Johnson",
    email: "mike.j@email.com",
    passwordhash: "hash3",
    creationdate: null,
    database: "us" as DatabaseOption,
  },
  {
    username: "user4_jp",
    fullname: "Yuki Tanaka",
    email: "yuki.t@email.com",
    passwordhash: "hash4",
    creationdate: null,
    database: "jp" as DatabaseOption,
  },
  {
    username: "user5_uk",
    fullname: "Emma Wilson",
    email: "emma.w@email.com",
    passwordhash: "hash5",
    creationdate: null,
    database: "uk" as DatabaseOption,
  },
  {
    username: "user6_de",
    fullname: "Hans Mueller",
    email: "hans.m@email.com",
    passwordhash: "hash6",
    creationdate: null,
    database: "de" as DatabaseOption,
  },
  {
    username: "user7_za",
    fullname: "Sarah Brown",
    email: "sarah.b@email.com",
    passwordhash: "hash7",
    creationdate: null,
    database: "za" as DatabaseOption,
  },
  {
    username: "user8_br",
    fullname: "Pedro Santos",
    email: "pedro.s@email.com",
    passwordhash: "hash8",
    creationdate: null,
    database: "br" as DatabaseOption,
  },
  {
    username: "user9_us",
    fullname: "Lisa Davis",
    email: "lisa.d@email.com",
    passwordhash: "hash9",
    creationdate: null,
    database: "us" as DatabaseOption,
  },
  {
    username: "user10_jp",
    fullname: "Kenji Sato",
    email: "kenji.s@email.com",
    passwordhash: "hash10",
    creationdate: null,
    database: "jp" as DatabaseOption,
  },
  {
    username: "user11_uk",
    fullname: "James Taylor",
    email: "james.t@email.com",
    passwordhash: "hash11",
    creationdate: null,
    database: "uk" as DatabaseOption,
  },
  {
    username: "user12_de",
    fullname: "Anna Schmidt",
    email: "anna.s@email.com",
    passwordhash: "hash12",
    creationdate: null,
    database: "de" as DatabaseOption,
  },
  {
    username: "user13_za",
    fullname: "David Green",
    email: "david.g@email.com",
    passwordhash: "hash13",
    creationdate: null,
    database: "za" as DatabaseOption,
  },
  {
    username: "user14_br",
    fullname: "Ana Costa",
    email: "ana.c@email.com",
    passwordhash: "hash14",
    creationdate: null,
    database: "br" as DatabaseOption,
  },
  {
    username: "user15_us",
    fullname: "Tom Wilson",
    email: "tom.w@email.com",
    passwordhash: "hash15",
    creationdate: null,
    database: "us" as DatabaseOption,
  },
  {
    username: "user16_jp",
    fullname: "Hiro Yamamoto",
    email: "hiro.y@email.com",
    passwordhash: "hash16",
    creationdate: null,
    database: "jp" as DatabaseOption,
  },
  {
    username: "user17_uk",
    fullname: "Oliver Brown",
    email: "oliver.b@email.com",
    passwordhash: "hash17",
    creationdate: null,
    database: "uk" as DatabaseOption,
  },
  {
    username: "user18_de",
    fullname: "Laura Weber",
    email: "laura.w@email.com",
    passwordhash: "hash18",
    creationdate: null,
    database: "de" as DatabaseOption,
  },
  {
    username: "user19_za",
    fullname: "Michael Adams",
    email: "michael.a@email.com",
    passwordhash: "hash19",
    creationdate: null,
    database: "za" as DatabaseOption,
  },
  {
    username: "user20_br",
    fullname: "Julia Lima",
    email: "julia.l@email.com",
    passwordhash: "hash20",
    creationdate: null,
    database: "br" as DatabaseOption,
  },
];

export default sampleUsers;
